[versions]
agp = "8.0.2"
kotlin = "1.9.10"
dependency-analysis = "1.21.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
compose-bom = "2023.03.00"
navigation-compose = "2.7.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dependencyAnalysis = {id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis"}

